"""initial_all_tables

Revision ID: 0bcfe82286b6
Revises: 
Create Date: 2026-06-02 20:13:49.292814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import UUIDChar

# revision identifiers, used by Alembic.
revision: str = '0bcfe82286b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('personas',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('user_id', UUIDChar(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('gift_ideas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_persona_id'), 'actions', ['persona_id'], unique=False)
    op.create_table('briefings',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('occasion', sa.String(length=30), nullable=False),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('recent_highlights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefings_persona_id'), 'briefings', ['persona_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('user_id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_persona_id'), 'events', ['persona_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_persona_id'), 'observations', ['persona_id'], unique=False)
    op.create_table('persona_insights',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('gift_suggestions', sa.Text(), nullable=True),
    sa.Column('emotion_trend', sa.JSON(), nullable=True),
    sa.Column('interest_trends', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('persona_memories',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_memories_category'), 'persona_memories', ['category'], unique=False)
    op.create_index(op.f('ix_persona_memories_persona_id'), 'persona_memories', ['persona_id'], unique=False)
    op.create_table('persona_relationships',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('source_persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('target_persona_id', UUIDChar(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('strength_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_relationships_source_persona_id'), 'persona_relationships', ['source_persona_id'], unique=False)
    op.create_index(op.f('ix_persona_relationships_target_persona_id'), 'persona_relationships', ['target_persona_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('session_id', UUIDChar(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('event_reminders',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('event_id', UUIDChar(length=36), nullable=False),
    sa.Column('remind_before_days', sa.Integer(), nullable=False),
    sa.Column('reminded_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_reminders_event_id'), 'event_reminders', ['event_id'], unique=False)
    op.create_table('memory_sources',
    sa.Column('id', UUIDChar(length=36), nullable=False),
    sa.Column('memory_id', UUIDChar(length=36), nullable=False),
    sa.Column('chat_message_id', UUIDChar(length=36), nullable=True),
    sa.Column('observation_id', UUIDChar(length=36), nullable=True),
    sa.Column('created_from', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memory_id'], ['persona_memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_sources_memory_id'), 'memory_sources', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_sources_memory_id'), table_name='memory_sources')
    op.drop_table('memory_sources')
    op.drop_index(op.f('ix_event_reminders_event_id'), table_name='event_reminders')
    op.drop_table('event_reminders')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_persona_relationships_target_persona_id'), table_name='persona_relationships')
    op.drop_index(op.f('ix_persona_relationships_source_persona_id'), table_name='persona_relationships')
    op.drop_table('persona_relationships')
    op.drop_index(op.f('ix_persona_memories_persona_id'), table_name='persona_memories')
    op.drop_index(op.f('ix_persona_memories_category'), table_name='persona_memories')
    op.drop_table('persona_memories')
    op.drop_table('persona_insights')
    op.drop_index(op.f('ix_observations_persona_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_events_persona_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_briefings_persona_id'), table_name='briefings')
    op.drop_table('briefings')
    op.drop_index(op.f('ix_actions_persona_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
