"""add_memory_confidence_fields

Revision ID: df6f52e978b4
Revises: 0bcfe82286b6
Create Date: 2026-06-02 22:31:40.879430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6f52e978b4'
down_revision: Union[str, Sequence[str], None] = '0bcfe82286b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona_memories', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('persona_memories', sa.Column('last_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona_memories', 'last_confirmed_at')
    op.drop_column('persona_memories', 'confidence_score')
    # ### end Alembic commands ###
